# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36abcc02d3c1f0ee3e5d227dfdd845fa7689487161ba90c83ad81958784ec8e58bbffa045cd53bd8b882fec38c5f8389eca8de14dfeba2acdd7eed718af1e9d

test:
  secret_key_base: 8c2ce61475c65530d2a13e77132f54e1e6176dbbdc7f072e9c6c41a9590807250c6051f458ab2a5212978e5ea1e8d8edda5c0619f748893813db150d73818a7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
